extends Resource

var list = {
	"Betrayer": {
		"Betrayer": [["Munanyou"], "<NO-TITLE>"],
	
		"nok": [["Munanyou"], "[color=#006aff]The First and Final Judge[/color]"],
		"WriterNat": [["Munanyou"], "Stormblessed"],
		"steph": [["Munanyou"], "Stormblessed"],
		"Mana": [["Munanyou"], "Stormblessed"],
		"HitsuuDesu": [["Munanyou"], "Stormblessed"],
		"Cherry": [["Munanyou"], "Stormblessed"],
		"Ataz": [["Munanyou"], "[color=#006aff]The True Victor[/color]"],
		"Pres": [["Munanyou"], "The Seed of Doubt"],
		"Death": [["Munanyou"], "Stormblessed"],
		"soopernoob": [["Munanyou"], "Stormblessed"],
		"Nezriani": [["Munanyou"], "Stormblessed"],
		"N.O.X": [["Munanyou"], "Unerring Judge"],
		"Draedon": [["Munanyou"], "Honorable Supporter... with some random characters on the end"],
		"Korbus": [["Munanyou"], "Stormblessed"],
		"THExplosion24": [["Munanyou"], "Harbinger of Devastation"],
		"BaffledFoxtail": [["Munanyou"], "Really god damn confused Fox"],
		"CTM9001": [["Munanyou"], "Justifying their Own Existence"],
		"samuraiarceus": [["Munanyou"], "Oni Born under Sakura Blooms"],
		"Script": [["Munanyou"], "Knows what She's Doing"],
		"krankyz": [["Munanyou"], "Moonlit Blade"],
		"Furious": [["Munanyou"], "The Dark Prince of Nothing"],
		"escafaidhe": [["Munanyou"], "A Friend from the Dark"],
		"system__shutdown": [["Munanyou"], "Tarnished Blood's Absolution"],
		"TriGambit": [["Munanyou"], "The Gambit"],
		"LostSky": [["Munanyou"], "Celestial Wayfarer"],
		"9 + 9 = 12": [["Munanyou"], "The Middle Little Brother"],
	},

	"Colossus": {
		"Colossus": [["Astaroth"], "<NO-TITLE>"],
	
		"nok": [["Astaroth"], "[color=#ff8933]The God-Given Right to Rule[/color]"],
		"Cherry": [["Astaroth"], "Calamitous Wrath"],
		"Pres": [["Astaroth"], "The Seed of Doubt"],
		"soopernoon": [["Astaroth"], "Calamitous Wrath"],
		"Death": [["Astaroth"], "Calamitous Wrath"],
		"N.O.X": [["Astaroth"], "Calamitous Wrath"],
		"SpadesofAce49": [["Astaroth"], "Calamitous Wrath"],
		"THExplosion24": [["Astaroth"], "Seeker of the True Flame"],
		"Mana": [["Astaroth"], "Calamitous Wrath"],
		"samuraiarceus": [["Astaroth"], "Calamitous Wrath"],
		"Draedon": [["Astaroth"], "Looks Better with a Hood"],
		"heeruv": [["Astaroth"], "Sol ColossusGuy"],
		"Mahoraga": [["Astaroth"], "Calamitous Wrath"],
		"Furious": [["Astaroth"], "The Dark Prince of Nothing"],
		"Septite": [["Astaroth"], "Sat Upon the Throne of Brimstone"],
		"CTM9001": [["Astaroth"], "Forsaken, Ceaseless Blaze"],
		"Trinity": [["Astaroth"], "Immovable Force"],
		"Emy": [["Astaroth"], "Abandoned, Accused, Arisen"],
		"Eminence": [["Astaroth"], "Sovereign Monarch"],
		"TriGambit": [["Astaroth"], "Unwavering Perseverance"],
		"jonico404": [["Astaroth"], "Warrior of Liberation"],
		"Script": [["Astaroth"], "Public Annihilation"],
		"AceOfFlames": [["Astaroth"], "The Cursed Star"],
		"Kirbymini": [["Astaroth"], "Path of the Great Storm"],
		"Eyl": [["Astaroth"], "Calamitous Wrath"],
		"yakke1113": [["Astaroth"], "Calamitous Wrath"],
		"june_": [["Astaroth"], "Cras Es Noster"],
		"Medi": [["Astaroth"], "Known F*cker"],
		"Hayabo-of-the-so": [["Astaroth"], "General of a Hundred Victories"],
		"MaoNao": [["Astaroth"], "The WAH's Reaper"],
		"Jet_Motivation": [["Astaroth"], "Deepwoken"],
		"system__shutdown": [["Astaroth"], "Tarnished Blood's Absolution"],
		"ANB1S": [["Astaroth"], "Overlord"],
		"Mist": [["Astaroth"], "Ominous Creature"],
		"krankyz": [["Astaroth"], "Seraph of Calamity"],
		"Tust": [["Astaroth"], "Greatest Lemon"],
		"BaffledFoxtail": [["Astaroth"], "Paragon"],
		"Ozzatron": [["Astaroth"], "Cynosure of Hatred"],
		"playersans21": [["Astaroth"], "The Demented One"],
		"Babyback": [["Astaroth"], "Natural Disaster"],
		"TheSolarInferno": [["Astaroth"], "The Endless Void"],
		"A3THER": [["Astaroth"], "Calamitous Wrath"],
		"visualoverload": [["Astaroth"], "Fiend Risen under the Roaring Moon"],
		"9chnn": [["Astaroth"], "Bearer of the Boundless Blade"],
		"terraprivm": [["Astaroth"], "The Easiest Enemy"],
		"16bit__": [["Astaroth"], "Joy Unrelenting and Forever"],
		"Abraços": [["Astaroth"], "Lost From Light"],
		"LostSky": [["Astaroth"], "Celestial Wayfarer"],
		"9 + 9 = 12": [["Astaroth"], "The Middle Little Brother"],
	},

	"Psycho": {
		"Psycho": [["Aimorrago"], "<NO-TITLE>"],
	
		"nok": [["Aimorrago", "Guillotine"], "[color=#FF0000]Blessed is the Blood[/color]"],
		"Cherry": [["Aimorrago"], "The Knife Chooses"],
		"Mana": [["Aimorrago"], "The Knife Chooses"],
		"THExplosion24": [["Aimorrago"], "Ascendant Being"],
		"MaoNao": [["Aimorrago"], "The WAH's Disciple"],
		"Draedon": [["Aimorrago"], "Architect of Steel and Stars"],
		"soopernoob": [["Aimorrago"], "Your Worst Nightmare"],
		"N.O.X": [["Aimorrago"], "The Unerring"],
		"CTM9001": [["Aimorrago"], "[color=#00FF00]Se Hai Timore Del Vero[/color]"],
		"samuraiarceus": [["Aimorrago"], "Oni Born under Sakura Blooms"],
		"musicofdeawea": [["Aimorrago"], "Nun's Rebound"],
		"Angel Chuu": [["Aimorrago"], "Void Ripper"],
		"TriGambit": [["Aimorrago"], "Persevering Insanity"],
		"Korbus": [["Aimorrago"], "Puppet of the Onimusha"],
		"Sleepy_Dorm": [["Aimorrago"], "British Citizen"],
		"Skillshare": [["Aimorrago"], "Dreor, Cruor, and Sanguine Incarnated"],
		"Mist": [["Aimorrago"], "Voiceless Obsession"],
		"Kirbymini": [["Aimorrago"], "Unshackled Sin"],
		"Furious": [["Aimorrago"], "The Dark Prince of Nothing"],
		"Nezriani": [["Aimorrago"], "Risk vs. Reward"],
		"Dreadnoughtus": [["Aimorrago"], "Scourge of Rage"],
		"MCHurt12": [["Aimorrago"], "The Red Dark Star"],
		"Lifeblood": [["Aimorrago"], "Joni's Blessing"],
		"TheSolarInferno": [["Aimorrago"], "Self-Proclaimed Spite"],
		"system__shutdown": [["Aimorrago"], "Tarnished Blood's Absolution"],
		"Omegalord9000": [["Aimorrago"], "Abyssal Sovereign"],
		"Pres": [["Aimorrago"], "The Seed of Doubt"],
		"Script": [["Aimorrago"], "A U T I S M"],
		"absolutely tutoumi": [["Aimorrago"], "The Strongest Pubber"],
		"Captain Dramillion": [["Aimorrago"], "The Inkfake Pirate"],
		"THIS IS SPARTA Of Pyroland": [["Aimorrago"], "Battle Fought Bleeding"],
		"ANB1S": [["Aimorrago"], "Overlord"],
		"krankyz": [["Aimorrago"], "Seraph of Calamity"],
		"BaffledFoxtail": [["Aimorrago"], "Paragon"],
		"playersans21": [["Aimorrago"], "The Demented One"],
		"Medi": [["Aimorrago"], "Known F*cker"],
		"Hayabo-of-the-so": [["Aimorrago"], "General of a Hundred Victories"],
		"Babyback": [["Aimorrago"], "Stains of Time"],
		"A3THER": [["Aimorrago"], "The Knife Chooses"],
		"ssjultrainstinct224": [["Aimorrago"], "The Knife Chooses"],
		"1majvvi1": [["Aimorrago"], "jvvi"],
		"Anomalous Shu": [["Aimorrago"], "The Challenger"],
		"LostSky": [["Aimorrago"], "Celestial Wayfarer"],
		"9 + 9 = 12": [["Aimorrago"], "The Middle Little Brother"],
	},

	"Hellsaint": {
		"Hellsaint": [["Camila"], "<NO-TITLE>"],
	
		"nok": [["Camila"], "[color=#ff0044]Developer & Death Bringer[/color]"],
		"WriterNat": [["Camila"], "¿Who am I?"],
		"Pres": [["Camila"], "The Seed of Doubt"],
		"CTM9001": [["Camila"], "Shredding Hearts into Rose Petals"],
		"Eminence": [["Camila"], "Demon Emperor"],
		"Lycan572": [["Camila"], "Trigger Happy Blood Fiend"],
		"samuraiarceus": [["Camila"], "Oni Born Under Sakura Blooms"],
		"MaoNao": [["Camila"], "The Will of WAH"],
		"Cherry": [["Camila"], "Ill-born Struggler"],
		"MuttDud": [["Camila"], "Supporter"],
		"Draedon": [["Camila"], "Architect of Steel and Stars"],
		"Diet_Bleach": [["Camila"], "Blood B*tch"],
		"Mana": [["Camila"], "Herrscher"],
		"Death": [["Camila"], "The One Waiting at the End"],
		"N.O.X": [["Camila"], "At the End of Everything, Only He Remains"],
		"soopernoob": [["Camila"], "The last Mofogyu in search of Earthend"],
		"MCHurt12": [["Camila"], "The Blue Dark Star"],
		"THExplosion24": [["Camila"], "Observer Forced Upon the Chaos"],
		"Script": [["Camila"], "Playful Pubstomper"],
		"Septite": [["Camila"], "Sat Upon the Throne of Brimstone"],
		"june_": [["Camila"], "Supporter"],
		"Shaygar": [["Camila"], "Seer of Sights"],
		"joshuahuff34": [["Camila"], "Supporter"],
		"Anna Mae": [["Camila"], "Supporter"],
		"inconsistent": [["Camila"], "Supporter"],
		"visualoverload": [["Camila"], "Fiend Risen Under the Roaring Moon"],
		"Mahoraga": [["Camila"], "With This Treasure I Summon..."],
		"Omegalord9000": [["Camila"], "Abyssal Sovereign"],
		"Rere3419": [["Camila"], "Happy Supporter"],
		"silicathefox": [["Camila"], "Frozen Supporter"],
		"HomestyleCrispeez": [["Camila"], "The Crispiest Bite"],
		"Korbus": [["Camila"], "First Revenant of Hengoku"],
		"Medi": [["Camila"], "Unbreakable Heart of Gold"],
		"jonesmd": [["Camila"], "Supporter"],
		"Dreadnoughtus": [["Camila"], "Scourge Of Rage"],
		"aridavis07": [["Camila"], "Supporter"],
		"odaciousL": [["Camila"], "The One and Lonely"],
		"Mikadzuki": [["Camila"], "Argalia"],
		"Dovahderpy": [["Camila"], "Spirit of Vengance"],
		"OneHitTalon": [["Camila"], "The God Wind Rabbit"],
		"Kirbymini": [["Camila"], "The Hollow's Abyss"],
		"scrimblo bingus": [["Camila"], "goober"],
		"GWAM": [["Camila"], "The Voices In The Void"],
		"TriGambit": [["Camila"], "Undying Soul"],
		"Angel Chuu": [["Camila"], "God of Creation"],
		"Mist": [["Camila"], "Kidnapper of Cherries"],
		"absolutely tutoumi": [["Camila"], "The Strongest Pubber"],
		"PixelTimesTwo": [["Camila"], "Certified Goofball"],
		"Trinity": [["Camila"], "Needs It"],
		"yakke1113": [["Camila"], "Fishy Business"],
		"Furious": [["Camila"], "The Dark Prince of Nothing"],
		"TheSolarInferno": [["Camila"], "The Collapsing Blight"],
		"MaxSmash09": [["Camila"], "Second Kindred Bloodfiend"],
		"system__shutdown": [["Camila"], "Tarnished Blood's Absolution"],
		"ANB1S": [["Camila"], "Overlord"],
		"ssjultrainstinct224": [["Camila"], "Supporter"],
		"BaffledFoxtail": [["Camila"], "Paragon"],
		"krankyz": [["Camila"], "God's Chosen Emperor"],
		"1majvvi1": [["Camila"], "jvvi"],
		"16bit__": [["Camila"], "Joy Unrelenting and Forever"],
		"LostSky": [["Camila"], "Celestial Wayfarer"],
		"9 + 9 = 12": [["Camila"], "The Middle Little Brother"],
	}
}
