var values = {
	"Hellsaint": [["Camila"], "<NO-TITLE>"],
	
	#	--
	"nok": [["Camila"], "Developer & Death Bringer"],
	"WriterNat": [["Camila"], "¿Who am I?"],
	"Pres": [["Camila"], "The Seed of Doubt"],
	"CTM9001": [["Camila"], "Shredding Hearts into Rose Petals"],
	"Eminence": [["Camila"], "Demon Emperor"],
	"Lycan572": [["Camila"], "Trigger Happy Blood Fiend"],	#	<-- Dum Bnuy (unkown_anomaly)
	"samuraiarceus": [["Camila"], "Oni Born Under Sakura Blooms"],
	"MaoNao": [["Camila"], "The Will of WAH"],
	"Cherry": [["Camila"], "Ill-born Struggler"],
	"MuttDud": [["Camila"], "Supporter"],
	"Draedon": [["Camila"], "Architect of Steel and Stars"],
	"Diet_Bleach": [["Camila"], "Blood B*tch"],
	"Mana": [["Camila"], "Herrscher"],
	"Death": [["Camila"], "The One Waiting at the End"],
	"N.O.X": [["Camila"], "At the End of Everything, Only He Remains"],
	"soopernoob": [["Camila"], "The last Mofogyu in search of Earthend"],
	"MCHurt12": [["Camila"], "The Blue Dark Star"],
	"THExplosion24": [["Camila"], "Observer Forced Upon the Chaos"],
	"Script": [["Camila"], "Playful Pubstomper"],
	"Septite": [["Camila"], "Sat Upon the Throne of Brimstone"],
	"june_": [["Camila"], "Supporter"],
	"Shaygar": [["Camila"], "Seer of Sights"],
	"joshuahuff34": [["Camila"], "Supporter"],
	"Anna Mae": [["Camila"], "Supporter"],
	"inconsistent": [["Camila"], "Supporter"],
	"visualoverload": [["Camila"], "Fiend Risen Under the Roaring Moon"],
	"Mahoraga": [["Camila"], "With This Treasure I Summon..."],
	"Omegalord9000": [["Camila"], "Abyssal Sovereign"],
	"Rere3419": [["Camila"], "Happy Supporter"],
	"silicathefox": [["Camila"], "Frozen Supporter"],
	"HomestyleCrispeez": [["Camila"], "The Crispiest Bite"],
	"Korbus": [["Camila"], "First Revenant of Hengoku"],
	"Medi": [["Camila"], "Unbreakable Heart of Gold"],
	"jonesmd": [["Camila"], "Supporter"],
	"Dreadnoughtus": [["Camila"], "Scourge Of Rage"],
	"aridavis07": [["Camila"], "Supporter"],
	"odaciousL": [["Camila"], "The One and Lonely"],
	"Mikadzuki": [["Camila"], "Argalia"],
	"Dovahderpy": [["Camila"], "Spirit of Vengance"],
	"OneHitTalon": [["Camila"], "The God Wind Rabbit"],
	"Kirbymini": [["Camila"], "The Hollow's Abyss"],
	"scrimblo bingus": [["Camila"], "goober"],
	"GWAM": [["Camila"], "The Voices In The Void"],
	"TriGambit": [["Camila"], "Undying Soul"],
	"Angel Chuu": [["Camila"], "God of Creation"],
	"Mist": [["Camila"], "Kidnapper of Cherries"],
	"absolutely tutoumi": [["Camila"], "The Strongest Pubber"],
	"PixelTimesTwo": [["Camila"], "Certified Goofball"],
	"Trinity": [["Camila"], "Needs It"],
	"yakke1113": [["Camila"], "Fishy Business"],
	"Furious": [["Camila"], "The Dark Prince of Nothing"],
	"TheSolarInferno": [["Camila"], "The Collapsing Blight"],
	"MaxSmash09": [["Camila"], "Second Kindred Bloodfiend"],
	"system__shutdown": [["Camila"], "Tarnished Blood's Absolution"],
	"ANB1S": [["Camila"], "Overlord"],
	"ssjultrainstinct224": [["Camila"], "Supporter"],
	"BaffledFoxtail": [["Camila"], "Paragon"],
	"krankyz": [["Camila"], "God's Chosen Emperor"],
	"1majvvi1": [["Camila"], "jvvi"],
}
